apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: "2026-04-08T10:16:57Z"
  name: dev-quota
  namespace: dev
spec:
  hard:
    cpu: "1"
    memory: 500Mi
    pods: "2"
    services: "3"
status:
  hard:
    cpu: "1"
    memory: 500Mi
    pods: "2"
    services: "3"

