apiVersion: v1
kind: Pod
metadata:
  name: guarantee
  labels:
   app: web
   env: dev
spec:
  containers:
  - name: guarantee
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"